    name: CI-CD Pipeline
    env:
      ARTIFACT_NAME: csye6225-webapp-${{ github.sha }}.zip
      CODEDEPLOY_APPLICATION_NAME: csye6225-webapp
      CODEDEPLOY_APPLICATION_DEPLOYMENT_GROUP_NAME: csye6225-webapp-deployment
      AWS_REGION: us-east-1
    on:
      pull_request:
        branches:
        - main
        - master
    jobs:
      ci_cd:
        runs-on: ubuntu-latest
        
        steps:
        - uses: actions/checkout@v2
        
        - name: Set up JDK 1.8
          uses: actions/setup-java@v1
          with:
            java-version: 1.8
        
        - name: Build with Maven
          run: | 
            cd CloudNativeWebApp && ./mvnw clean install
        
        - name: Build Deployment Artifact
          run: |
            mkdir codedeploy_artifact
            zip -r ${{ env.ARTIFACT_NAME }} target/CloudNativeWebApp-0.0.1-SNAPSHOT.jar codedeploy/*.sh appspec.yml
            pwd
            ls -al
            mv ${{ env.ARTIFACT_NAME }} codedeploy_artifact/
            ls -al
            pwd
            cd codedepoly_artifact
            pwd
            ls -al
            cd ..
            pwd
            ls -al
        
        - name: Configure AWS credentials
          uses: aws-actions/configure-aws-credentials@v1
          with:
            aws-access-key-id: ${{ AWS_ACCESS_KEY_ID }}
            aws-secret-access-key: ${{ AWS_SECRET_ACCESS_KEY }}
            aws-region: ${{ env.AWS_REGION }}
        
        - name: Copy Artifact to S3
          run: |
            aws s3 sync ./codedeploy_artifact s3://codedeploy.6225csyekeyuliu.me

        - name: CodeDeploy API call
          run: |
            output=$(aws deploy create-deployment \
              --application-name ${{ env.CODEDEPLOY_APPLICATION_NAME }} \
              --region ${{ env.AWS_REGION }} \
              --output json)

              echo $output

              dId=$(echo $output | jq -r '.deploymentId')

              aws deploy wait deployment-successful --deployment-id $dId
            




